### ISSUE TITLE
Synthesising to an FPGA

### ISSUE THREAD

**Issue by hasindu2008** [TimD1/SquiggleFilter#1]
Hi 
I saw your poster on London Calling and read through your paper. The performance seems to be really promising. I am trying to synthesise your project at https://github.com/TimD1/SquiggleFilter/blob/master/design/verilog_v2.rar to a Xilinx Zedboard. However, this top-level module  (testbench_top) doesn't seem to be synthesisable. Could you please direct me to instructions on how to synthesise this?

I have MINKNOW already running on a Jetson Xavier and have the reference sequence (SARS-CoV-2) on the Zed board SD card. I am interested in getting the SquiggleFIlter (the marked part below) to run the on the FPGA. 
<img width="374" alt="image" src="https://user-images.githubusercontent.com/12987163/169741335-fd24d43f-3ec0-4b61-9af5-2749adb1b48b.png">

**Comment by harisankarsadasivan** [comment]
@hasindu2008, Thanks for your interest in our work and reaching out to us. Your observation is correct. 
testbench_top is a wrapper over SquiggleFilter module for the functional verification of the module and hence, the testbench wrapper may not be syntheziable on an FPGA while the hardware modules are. We synthesized SquiggleFilter as a stand-alone entity using a 28nm TSMC tech for the ASIC results on the paper. However, if behavioral simulation interests you and want to try this out, you may please review the Section: "Behavioral simulation using the testbench". 

However, we have not tested the fully integrated solution with the interconnects (your encircled region).
We envision a fully integrated system with high speed on-chip interconnects and a shared memory bus that connects the DRAM to the ARM core and the accelerator, resulting in our modelled latencies.

**Comment by hasindu2008** [comment]
@harisankarsadasivan Thank you very much for the quick response.  
It seems like as you say the testbench wrapper is not synthesisable, but I tried synthesising the warper_top. Going through the code (constants.vh) I see that there is an ifdef statement for synthesis and the default query size seems to be set to 2. I guess this should be changed to 2000 to match the configuration shown in the paper?

**Comment by harisankarsadasivan** [comment]
@hasindu2008 
Yes, we defined the "SYNTH" macro and test-synthesized for a smaller query size on the FPGA before synthesizing for 2000 for the ASIC. 
Please note that we independently synthesized the normalizer_top and the warper_top modules.
